server:
  port: 9411
spring:
  application:
    name: cloud-zipkin-server
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://cloud.server.one:8761/eureka/,http://cloud.server.two:8762/eureka/,http://cloud.server.three:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
management:
  metrics:
    web:
      server:
        auto-time-requests: false