server:
   port: 8761
   undertow:
      io-threads: 4
      worker-threads: 20
      buffer-size: 1024
      direct-buffers: true
spring:
   application:
      name: cloud-eureka-server
eureka:
   instance:
      hostname: 127.0.0.1
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
   client:
      healthcheck:
         enabled: true
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/